mysite/blog/urls.py
from froala_editor import views
from unicodedata import name
from urllib.parse import urlparse
from django.urls import path,include
from . import views

urlpatterns = [
    path('froala_editor/',include('froala_editor.urls')),
    path('' , views.home , name='home'),
    path('signup' , views.UserSignUp , name= 'signup' ),
    path('login' , views.UserLogin , name='login'),
    path('logout' ,views.UserLogout , name='logout'),
    path('dashboard' , views.UserDashboard , name='dashboard'),
    path('userupdate' , views.Userupdate , name="userupdate") ,
    path('userpasswordchange' , views.UserPasswordChange , name= 'userpasswordchange'),
    path('post/<slug:slug>' , views.detailedPost , name='detailPost'),
    path('postcreation' , views.UserPostCreation , name='postcreation'),
    path('postdelete/<slug:slug>' , views.Userpostdelete , name='postdelete'),
    path('comment/<slug>' , views.UserComment , name= 'comment'),
    path('favourite' , views.addFavourite , name= 'addfavourite'),
    path('allfavpost' , views.allFavourite , name='allfavourite'),
    path('like-post' , views.Like_post , name='like-post'),
    path('userImageUpdate' , views.userImageUpdate , name= 'userImageUpdate'),
    path('Userportfolio/<int:userid>' , views.portfolio , name = 'portfolio'),
    path('follow' ,views.followUnfollow , name='follow'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL , document_root= settings.MEDIA_ROOT)

handler404 = "mysite.views.page_not_found"

mysite/blog/models.py
from distutils.command.upload import upload
from email.policy import default

from django.db import models
from froala_editor.fields import FroalaField
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=40)
    slug = models.SlugField(unique=True)
    date = models.DateField(auto_now=True)
    image= models.ImageField(upload_to='image')
    exerpt= models.TextField(max_length=150)
    # content= models.TextField()
    content= FroalaField()
    like = models.IntegerField(default=0)

    author= models.ForeignKey(User,on_delete=models.CASCADE,related_name='author')
    tag = models.ManyToManyField("Tags",related_name='tag')

    def __str__(self):
        return self.title



class Tags(models.Model):
    batch = models.CharField(max_length=20)

    def __str__(self):
        return self.batch


class Comments(models.Model):
    comment_text = models.TextField(max_length=300)
    post= models.ForeignKey(Post ,on_delete=models.CASCADE ,related_name='post')
    author= models.ForeignKey(User ,default=None, on_delete=models.CASCADE , related_name='commentauthor')

    # def __str__(self):
    #     return self.post.title


class UserImage(models.Model):
    uimage= models.ImageField(upload_to='userimage' , default=None)
    aboutme = models.TextField(max_length=1300 , default='Please Write somthing about yourself.')
    designation = models.CharField(default='Unknown' ,max_length=50)
    youtube = models.URLField(max_length=300 ,default='https://www.youtube.com/')
    twiter  = models.URLField(max_length=300 ,default='https://twitter.com/')
    instagram = models.URLField(max_length=300 ,default='https://www.instagram.com/')
    author= models.OneToOneField(User , on_delete=models.CASCADE , related_name='userimg')

    follower= models.IntegerField(default=0)
    following= models.IntegerField(default=0)

    def __str__(self):
        return self.author.username



    # def save(self):
    #     super().save()

    #     img = Image.open(self.image.path) # Open image

    #     # resize image
    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size) # Resize image
    #         img.save(self.image.path) # Save it again and override the larger image



class LikesPost(models.Model):
    postId = models.IntegerField()
    username = models.CharField(max_length=200)



    def __str__(self):
        return self.username

class Follower(models.Model):
    user = models.CharField(max_length=100)
    follower=models.CharField(max_length=100) 

    def __str__(self):
        return self.user 

mysite/blog/forms.py
from cProfile import label
from dataclasses import field
from pyexpat import model
from django import forms
# from froala_editor.fields import FroalaField
from froala_editor.widgets import FroalaEditor
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User 

from .models import Post,Comments,UserImage


class UserSignupForm(UserCreationForm):
    password2= forms.CharField(label='Confirm password' , widget=forms.PasswordInput)
    class Meta:
        model= User 

        fields =['username' ,'first_name' , 'last_name' ,'email' ]
        labels = {'email':'Email' , 'first_name':'First Name', 'last_name':'Last Name'}

class UserUpdateForm(UserChangeForm):
    password= None

    class Meta:
        model= User
        fields = ['username' , 'first_name' , 'last_name' , 'email']

class UserPostForm(forms.ModelForm):
    content= forms.CharField(widget=FroalaEditor)
    class Meta:
        model = Post
        fields= ['title' ,'image' , 'exerpt' , 'content'  ,'tag' ]

class UserCommentform(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comment_text']
    
class userImageForm(forms.ModelForm):
  
    youtube = forms.URLField(required=False ,label='YouTube Channel')
    twiter = forms.URLField(required=False ,label='Twitter Id')
    instagram = forms.URLField(required=False ,label='Insatgram Id' )
    class Meta:
        model= UserImage
        fields = ['uimage','aboutme','designation','youtube','twiter','instagram']
        # required_fields =['aboutme','designation']
        labels= {
            'uimage':"User Image", 'aboutme':'About Me','designation':'Designation',
            
        }

mysite/blog/views.py
from django.core.exceptions import ObjectDoesNotExist

from django.http import JsonResponse
from django.shortcuts import render, HttpResponseRedirect 
from django.urls import reverse

from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group,User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UserChangeForm, \
     SetPasswordForm , PasswordChangeForm 
from django.contrib.auth import login,logout,authenticate,update_session_auth_hash
from django.contrib import messages

from .models import Post, Comments, Tags ,LikesPost ,UserImage ,Follower
from .forms import UserSignupForm , UserUpdateForm , UserPostForm ,UserCommentform,userImageForm

# Create your views here.




@login_required(login_url='login')
def followUnfollow(request):
    if request.method=='POST':
        follower_user= request.user
        follower_user_img = follower_user.userimg
        # print(follower_user_img.aboutme)
        user= User.objects.get(username= request.POST['user']) 
        user_img = user.userimg
        # print(user_img.aboutme)
        
        follo_list = Follower.objects.filter(follower=follower_user.username ,user= user.username)
        
        # print(follo_list)
        if len(follo_list)==0:
            new_foll = Follower(follower= follower_user.username ,user= user.username)
            new_foll.save()

            user_img.follower =user_img.follower+1 
            follower_user_img.following=follower_user_img.following + 1
            user_img.save()
            follower_user_img.save()
        else:
            follo_list[0].delete()
            
            user_img.follower = user_img.follower-1
            follower_user_img.following= follower_user_img.following-1 
            user_img.save()
            follower_user_img.save()
        return HttpResponseRedirect(reverse('portfolio' ,args=[user.id]))
    else:
        return HttpResponseRedirect(reverse('home'))





@login_required(login_url='login')
def portfolio(request,userid):
    user = User.objects.get(id = userid)
    userdetail = UserImage.objects.get(author= user)
    return render(request, 'blog/portfolio.html' , {
        'user':user,
        'userdetail':userdetail,
    })




def userImageUpdate(request):
    if request.user.is_authenticated:
        
        if request.method =='POST':
            try:
                if request.user.userimg:
                    fm = userImageForm(request.POST,request.FILES, instance=request.user.userimg)
                    if fm.is_valid():
                        img= fm.save(commit=False)
                        img.author = request.user
                        img.save()
                        return HttpResponseRedirect(reverse('dashboard'))
            except ObjectDoesNotExist:
                fm = userImageForm(request.POST,request.FILES)
                if fm.is_valid():
                    img= fm.save(commit=False)
                    img.author = request.user
                    img.save()
                    return HttpResponseRedirect(reverse('dashboard'))
        else:
            fm = userImageForm(instance=request.user.userimg)
        return render(request ,'blog/uploadimage.html' ,{
            'form':fm,
        })
    else:
        return HttpResponseRedirect(reverse('login'))


def allFavourite(request): 
    postid= request.session.get('favourite')
    if postid==None:
        all_fav_post=[]
    else:
        all_fav_post = Post.objects.filter(id__in =postid)

    have_fav= False
    if len(all_fav_post)>0:
        have_fav=True
    
    return render(request , 'blog/allfavouritepost.html' ,{
        'all_fav_post':all_fav_post,
        'have_fav':have_fav,
    })


def addFavourite(request):
    if request.user.is_authenticated:
        fav_post_id = int(request.POST['fav_post'])
        fav= request.session.get('favourite')
        if fav==None:
            fav= []
        if fav_post_id not in fav:
            fav.append(fav_post_id)
        else:
            fav.remove(fav_post_id)
        
        request.session['favourite'] = fav
        favpost= Post.objects.get(id=fav_post_id)
        return HttpResponseRedirect(reverse('detailPost' , args=[favpost.slug]))
    else:
        return HttpResponseRedirect(reverse('login'))



def isFav(request, id):
    is_fav = False
    fav = request.session.get('favourite')
    if fav !=None:
        if id in fav:
            is_fav=True
    return is_fav



def UserComment(request , slug):
    if request.user.is_authenticated:
        if request.method=="POST":
            fm = UserCommentform(request.POST)
            if fm.is_valid():
                targetpost= Post.objects.get(slug=slug)
                comment= fm.save(commit=False)
                comment.post= targetpost
                comment.author= request.user
                comment.save() 
                
        return HttpResponseRedirect(reverse('detailPost' , args=[slug]))

    else:
        return HttpResponseRedirect(reverse('login'))


@login_required(login_url='login')
def Like_post(request):
    if request.method =='GET':
        username= request.user.username
        post_id = request.GET.get('post_id')

        like_filter = LikesPost.objects.filter(postId=post_id , username= username).first()
        post =  Post.objects.get(id= post_id)
        total_like= 0
        if like_filter==None:
            newlike = LikesPost.objects.create(postId=post_id,username=username)
            newlike.save()
            post.like = post.like+1
            post.save()
            total_like= post.like

        else:
            like_filter.delete()
            post.like = post.like - 1
            post.save()
            total_like= post.like
        
        data={
            'likes':total_like
        }

    return JsonResponse(data)




# @login_required(login_url='login')
# def Like_post(request):
#     username= request.user.username
#     post_id = request.GET.get('post_id')

#     like_filter = LikesPost.objects.filter(postId=post_id , username= username).first()
#     post =  Post.objects.get(id= post_id)
#     if like_filter==None:
#         newlike = LikesPost.objects.create(postId=post_id,username=username)
#         newlike.save()
#         post.like = post.like+1
#         post.save()

#     else:
#         like_filter.delete()
#         post.like = post.like - 1
#         post.save()

#     return HttpResponseRedirect('/')

def Userpostdelete(request , slug):
    if request.user.is_authenticated:
        if request.method =="POST":
            post = Post.objects.get(slug=slug)
            if request.user== post.author:
                post.delete()
        
        return HttpResponseRedirect(reverse('dashboard'))

    else:
        return HttpResponseRedirect(reverse('login'))


def detailedPost(request , slug):
    post= Post.objects.get(slug=slug)
    tag= post.tag.all()
    is_fav = isFav(request,post.id)
    print(is_fav)
    comment= post.post.all()
    fm= UserCommentform()
    return render(request , 'blog/postdetail.html' , {
        'post':post,
        'tag':tag, 
        'form':fm,
        'comment':comment,
        'is_fav':is_fav,
    })


def slugCreation(arr):
    a = ''
    for i in range(len(arr)):
        if arr[i].isalnum() or arr[i]==' ':
            a+=arr[i]

    s= a.split()
    t= datetime.now()
    sl= str(t)
    sl= sl.replace(':' ,'-').replace(' ','-').replace('.','-')
    sl= '-'.join(s) +sl 
    return sl 


def UserPostCreation(request):
    if request.user.is_authenticated:
        if request.method =='POST':
        
            fm = UserPostForm(request.POST ,request.FILES)
            temp= request.POST['title']
            if fm.is_valid():
            
                new_post = fm.save(commit=False)
                new_post.author = request.user
                new_post.slug= slugCreation(str(temp))
                new_post.save()
                fm.save_m2m()
                
                messages.success(request , 'Post Created!')
                return HttpResponseRedirect('dashboard')

        else:
            fm = UserPostForm()

        return render(request , 'blog/postcreation.html' ,{
            'form':fm , 
        })

    else:
        return HttpResponseRedirect('login')




def UserDashboard(request):
    if request.user.is_authenticated:
        user_name = request.user
        # img= user_name.userimg.uimage
        all_post = request.user.author.all().order_by('-date')
        return render(request , 'blog/dashboard.html' , {
            'uname':user_name,
            'post':all_post,
        
        } )
    else:
        return HttpResponseRedirect('login')


def home(request):
    all_post= Post.objects.all().order_by('-date')
    have_post = True 
    if len(all_post)==0:
        have_post=False
    return render(request , 'blog/home.html' , {
        'post':all_post,
        'have_post':have_post,
    })

def UserSignUp(request):
    if request.method=='POST':
        
        fm = UserSignupForm(request.POST)
        uname = request.POST['username']
        existingUser = User.objects.filter(username=uname).first()
        if existingUser:
            return render(request , 'blog/signup.html' , {
                'form':fm, 'uname':'This username already exist!'
            })
        else:    
            if fm.is_valid():
                usr= fm.save()
                grp= Group.objects.get(name='blogger')
                usr.groups.add(grp)

                ###############
                # user_detail = UserImage(author= usr,uimage='https://www.dropbox.com/s/cbqm3pn7ae3gq3f/user-icon-jpg-21.jpg?dl=1')
                user_detail = UserImage(author= usr , uimage ='userimage/defaultuser.jpg')
                
                user_detail.save()
                ##########

                return HttpResponseRedirect('/')
    else:
        fm = UserSignupForm()

mysite/blog/templates/blog/allfavouritepost.html
{% extends 'base.html' %}
{% load static %}

{% block title %} 
    Favourite Posts 
{% endblock title %}
   
{% block style %}
    <link rel="stylesheet" href="{% static 'blog/css/post.css' %}">
{% endblock style %}


{% block content %}

    
    <div  class='favpost'>
        {% if have_fav %}
            <div class="flex-container posts">

                {% for post in all_fav_post %}
                    <div class="post_section">
                        {% include 'blog/include/include_post.html' %}
                    </div>
                    
                {% endfor %}
            </div>
        {% else %}
            <h2> You don't have any favourite Post yet!!!</h2>  
        {% endif %}
    </div>
    
{% endblock content %}

mysite/blog/templates/blog/dashboard.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    MyDashboard
{% endblock title %}

{% block style %}
     <link rel="stylesheet" href="{% static 'blog/css/post.css' %}">
     <link rel="stylesheet" href="{% static 'blog/css/dashboard.css' %}">
     
{% endblock style %}


{% block content %}

    <div class="flex-container author">
           
            <!-- <form class="author_img" action="" method="post">
                <img src="{{ uname.userimg.uimage.url }}" alt="Not fond">
            </form> -->
            {% if  uname.userimg.uimage.url is not None %}
                <a class='author_img' href="{% url 'userImageUpdate' %}"><img src="{{ uname.userimg.uimage.url }}"></a>
            {% else %}
                <a class='author_img' href="{% url 'userImageUpdate' %}"><img src="{% static 'blog/image/mine.png' %}" alt="Not fond"></a>
            {% endif %}

            
            <div class="author_details">
                {% comment %} <address><a href="mailto:{{uname.email}}">@{{uname.username}}</a></address> {% endcomment %}
                <address><a href="{% url 'portfolio' uname.id %}">@{{uname.username}}</a></address>
                

                {% if request.user.is_authenticated %}
                <a href="{% url 'userupdate' %}">Update Profile </a>
                {% endif %}
                {% if request.user.is_authenticated %}
                <a href="{% url 'userpasswordchange' %}">Update Password </a>
                {% endif %}

                {% if request.user.is_authenticated %}
                <a href="{% url 'postcreation' %}">Create Post </a>
                {% endif %}

            </div>

            
    </div>
  

    <div class="flex-container posts">

        {% for post in post %}

            <div class="post_section">
                {% include 'blog/include/include_post.html' %}
                
                <hr>
                <div class="like_del">
                    
                    {% if perms.blog.delete_post %}
                    
                    <form action="{% url 'postdelete' post.slug %}" method="post">
                        {% csrf_token %}
                        <button id="delete">Delete</button>
                    </form>
                        <a post_id={{post.id}} class='like_post'>Likes:<p id='{{post.id}}'>{{post.like}}</p></a>
                    {% endif %}
                
                
                        {% comment %} <a href="/like-post?post_id={{post.id}}">Like</a>: {{post.like}} {% endcomment %}

                </div>
                
            </div>
            
            
        {% endfor %}
        
        
    </div>





{% endblock content %}

mysite/blog/templates/blog/home.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Home 
{% endblock title %}


{% block style %}
    <link rel="stylesheet" href="{% static 'blog/css/post.css' %}">
{% endblock style %}


 
{% block content %}
   
    {% if have_post %}
        <div class="flex-container posts">

            {% for post in post %}
                <div class="post_section">
                    {% include 'blog/include/include_post.html' %}
                    <hr>
                    <div>
                        
                        <a post_id={{post.id}} class='like_post'>Like</a> : <p id='{{post.id}}'>{{post.like}}</p>
                        {% comment %} <a href="/like-post?post_id={{post.id}}" class='like_post'>Like</a> : {{post.like}}  {% endcomment %}
                        {% comment %} {% include 'blog/include/include_like.html' %} {% endcomment %}
                        <!-- <a href="/like-post?post_id={{post.id}}">Like</a> : {{post.like}} -->
                    </div>
                    
                </div>
                
            {% endfor %}
        </div>
    {% else %}
        <h2> No any Post Yet !!</h2>
    {% endif %}
    
    

{% endblock content %}
    

mysite/blog/templates/blog/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    LogIn Page
{% endblock title %}

{% block style %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300&family=Quicksand&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'blog/css/login.css' %}">

{% endblock style %}


{% block content %}
    
    

    <form action="" method="post">
        {% csrf_token %}
        <h3>Login Here</h3>
        {% for field in form %}
            <label>{{field.label}}</label>
            {{field}}
            {{field.errors}} <br>

        {% endfor %}
        <input type="submit" value="Log In">
    </form>
    
    
    

{% endblock content %}
    

mysite/blog/templates/blog/passwordupdate.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Password Update page 
{% endblock title %}

{% block style %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300&family=Quicksand&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'blog/css/login.css' %}">

{% endblock style %}

{% block content %}
    
    <form action="{% url 'userpasswordchange' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <label>{{field.label}}</label>
            {{field}}
            {{field.errors}} <br>

        {% endfor %}
        <input type="submit" value="Save">
    </form>
    
    
    

{% endblock content %}
    

mysite/blog/templates/blog/portfolio.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
 Author Page 
{% endblock  %}


{% block style %}
    <link rel="stylesheet" href="{% static 'blog/css/portfolio.css' %}">
{% endblock  %}


{% block content %}
    
    <section class="profile_container">
        <div class="profile_img_section">
            {% if userdetail.uimage %}
            <img class="profile_img-LG" src="{{ userdetail.uimage.url }}" />
            {% else %}
                <img class="profile_img-LG" src="https://cdn.idntimes.com/content-images/community/2020/10/122163576-262420488513552-863075192792965334-n-f95e3dd6d25d3618eb9f1b3b9bcc5796.jpg" />
            {% endif %}
            {% comment %} <img class="profile_img-LG" src="abcd.png" alt=""> {% endcomment %}
        </div>
    
        <div class="profile_desc_section">
            <h2>{{user.username}}</h2>
            <h3>{{userdetail.designation}}</h3>
            <p class="description"> {{userdetail.aboutme|linebreaks}} </p>
    
            <div class="interests">
                <h3>Interested Field</h3>
                <span class="interests_item">Technology</span>
                <span class="interests_item">Management</span>
                <span class="interests_item">Leadership</span>
            </div>
        </div>
    
    </section>
    
    <div class="info">
        
        <div class="follow">
            <p id="foll">Follower:{{userdetail.follower}}</p>
            <p id="foll">Following:{{userdetail.following}}</p>
            <form action="{% url 'follow' %}" method='POST'>
                {% csrf_token %}
                {% comment %} <input type="hidden" value="{{user}}" name="follower"> {% endcomment %}
                <input type="hidden" value="{{user.username}}" name="user">
                <button type="submit">Follow</button>
            </form>
        </div>

        
        
    </div>

    <div class="together">
        <h2 id="work">Let's work Together:</h2>
        <div class="media">
            
            <a href="{{userdetail.youtube}}" target="_blank" ><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z"/></svg></a>
            <a href="{{userdetail.instagram}}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"/></svg></a>
            <a href="{{userdetail.twiter}}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"/></svg></a>
            <a href="mailto:{{user.email}}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M464 64C490.5 64 512 85.49 512 112C512 127.1 504.9 141.3 492.8 150.4L275.2 313.6C263.8 322.1 248.2 322.1 236.8 313.6L19.2 150.4C7.113 141.3 0 127.1 0 112C0 85.49 21.49 64 48 64H464zM217.6 339.2C240.4 356.3 271.6 356.3 294.4 339.2L512 176V384C512 419.3 483.3 448 448 448H64C28.65 448 0 419.3 0 384V176L217.6 339.2z"/></svg></a>
        
        </div>
    </div>



{% endblock  %}